#!/bin/sh

# Copyright (C) 2015 Leif Johansson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
self=`basename $0`

ICI_CMD=$0
export ICI_CMD

usage ()
{
    echo "\
Usage: ici_req [-V] [-v] [-h] [--ip <ip>] [--dns <fqdn>] [--email <email>] [--uri <uri>] [<fqdn>]

ici_req is the request tool for the ici ca

  -v, --verbose             explain what is being done
  -h, --help                show this help text and exit
  -V, --version             show version information and exit

" 1>&2
}

ICI_OPENSSL=openssl
export ICI_OPENSSL

ICI_SUBJECT_DN=""
ICI_ALTNAMES=""
ICI_BITS="4096"


# Command line parsing.
{
    while test $# -gt 0; do
	if [ -z "$ICI_ALTNAMES" ]; then comma=; else comma=,; fi
	case "$1" in
	    --verbose | -v)
		ICI_VERBOSE=y
		shift ;;
	    --help | -h )
		usage
		exit 0 ;;
	    --version | -V )
		version
		exit 0 ;;
            --bits)
                ICI_BITS="$2"
                shift ;;
            --dns)
                ICI_ALTNAMES="DNS:$2$comma$ICI_ALTNAMES"
                fqdn="$2"
                shift ;;
            --ip)
                ICI_ALTNAMES="IP:$2$comma$ICI_ALTNAMES"
                shift ;;
            --email)
                ICI_ALTNAMES="email:$2$comma$ICI_ALTNAMES"
                shift ;;
            --uri)
                ICI_ALTNAMES="URI:$2$comma$ICI_ALTNAMES"
                shift ;;
	    -* )
		echo "$self: unknown option $1" 1>&2
		echo "Try 'ici_req --help' for more information." 1>&2
		exit 1 ;;
	    * )
		break ;;
	esac
        shift
    done

    export ICI_VERBOSE
}

export ICI_SUBJECT_DN ICI_TYPE ICI_ALTNAMES ICI_BITS

_trap ()
{
   err=$?
   if [ $err -ne 0 ]; then
      echo "--- cfg ---"
      cat $1
      echo "--- out ---"
      cat $2 
   fi
   rm -f $1
   rm -f $2
   exit $err
}

if [ $# -gt 0 ]; then
   fqdn="$1"; shift
   if [ -z "$ICI_ALTNAMES" ]; then comma=; else comma=,; fi
   ICI_ALTNAMES="DNS:$fqdn$comma$ICI_ALTNAMES"
fi

if [ -z "$ICI_ALTNAMES" ]; then
   echo "** warning: no altnames provided - did you forget your --dns|--ip|--email|--uri options?"
fi

cfg=`mktemp`
key=`mktemp`
csr=`mktemp`

c=""
sname=""
if [ ! -z "$fqdn" ]; then
   sname="$fqdn"
   c=`echo $fqdn | awk -F. '{ print toupper($NF) }'`
fi

trap '_trap $cfg $key $csr' EXIT

cat>$cfg<<EOC
[ req ]
default_bits           = $ICI_BITS
req_extensions         = req_extensions
distinguished_name     = req_dn

[ req_dn ]
CN="Common Name"
CN_default="$fqdn"
O="Organization Name"
C="Country Code"
C_default="$c"

[ req_extensions ]
EOC
if [ ! -z "$ICI_ALTNAMES" ]; then
cat>>$cfg<<EOC
subjectAltName          = $ICI_ALTNAMES
EOC
fi

$ICI_OPENSSL req -config $cfg -new -newkey rsa:${ICI_BITS} -reqexts req_extensions -sha256 -keyout $key -nodes -out $csr
if [ -z "$sname" ]; then
   sname=`$ICI_OPENSSL req -noout -subject < $csr |  sed 's/subject=//' | sha1sum`
fi
test -s $key -a -s $csr && mv $key "$sname.key" && mv $csr "$sname.csr"
echo "Successfully generated $sname.key and $sname.csr"
