#!/bin/sh

. $ICI_CA_DIR/ca.config

mkdir -p $ICI_CA_DIR/certs

if [ -z "${ICI_CRL_KEY_SLOT}" ]; then
   ICI_CRL_KEY_SLOT="${ICI_CA_KEY_SLOT}"
fi

if [ -z "${ICI_CRL_KEY_ID}" ]; then
   ICI_CRL_KEY_ID="${ICI_CA_KEY_ID}"
fi

$ICI_OPENSSL ca -gencrl -notext -batch \
   -config $ICI_CONFIG -engine pkcs11 -crl_extensions crl_extensions \
   -keyfile "${ICI_CRL_KEY_SLOT}:${ICI_CRL_KEY_ID}" -keyform engine \
   -crldays ${ICI_DAYS} -out "${ICI_CA_DIR}/crl.pem" >$log 2>&1
