#!/bin/sh

. $ICI_CA_DIR/ca.config

mkdir -p $ICI_CA_DIR/certs

cat /dev/urandom | tr -cd 'a-f0-9' | head -c 16 > $ICI_CA_DIR/serial

$ICI_OPENSSL ca -notext -batch -subj "$ICI_SUBJECT_DN" \
   -config $ICI_CONFIG -engine pkcs11 -extensions extensions \
   -keyfile "${ICI_CA_KEY_SLOT}:${ICI_CA_KEY_ID}" -keyform engine \
   -days ${ICI_DAYS} -outdir $ICI_CA_DIR/certs -in "$1"
