#!/bin/sh

. $ICI_CA_DIR/ca.config

mkdir -p $ICI_CA_DIR/certs

process_csr ()
{
    csr=$1
    name=$2
    nameopt=""
    if [ ! -z "$name" ]; then
	nameopt="-subj \"$name\""
    fi

    if [ "x$ICI_VERBOSE" = "xy" ]; then
	echo ""
	echo "$0: Processing CSR '$csr' for name '$name', nameopt '$nameopt'"
	openssl req -text < $csr
	echo ""
    fi

    CSR_ICI_CONFIG=`mktemp`
    cat $ICI_CONFIG > $CSR_ICI_CONFIG
    cat >> $CSR_ICI_CONFIG <<EOC

# Per-CSR configuration below
EOC

    if [ "x${ICI_CSR_ALTNAMES}" != "x" ]; then
	# Append subjectAltNames from CSR to the CSR_ICI_CONFIG
	dns_names="`openssl req -in "${csr}" -text -noout | grep DNS: | sed -e 's/DNS://g' -e 's/, / /g' -e 's/[^0-9a-zA-Z\. -]//g' | sort | uniq`"
	echo "$0: DNS subjectAltNames in CSR: ${dns_names}"

	echo "[ ${ICI_CSR_ALTNAMES} ]" >> $CSR_ICI_CONFIG
	i=1
	for n in $dns_names; do
            echo "DNS.${i} = ${n}" >> $CSR_ICI_CONFIG
	    i=`expr $i + 1`
	done
    fi

    set +x
    serial=`cat /dev/urandom | tr -cd 'a-f0-9' | head -c 16`
    echo $serial > $ICI_CA_DIR/serial
    $ICI_OPENSSL ca -notext -batch $nameopt \
		 -config $CSR_ICI_CONFIG -engine pkcs11 -extensions extensions \
		 -keyfile "pkcs11:token=${ICI_CA_KEY_TOKEN}" -keyform engine \
		 -days ${ICI_DAYS} -outdir $ICI_CA_DIR/certs -in "$csr"

    # Remember mapping between input filename and serial, for use in publish.d/50req-resp
    echo "${serial};${csr}" >> $ICI_CA_DIR/serial_db.txt

    if [ "x$ICI_VERBOSE" = "xy" ]; then
	echo ""
	echo "$0: Output file: $ICI_CA_DIR/certs/`cat $ICI_CA_DIR/serial`.pem"
    fi

    rm -f $CSR_ICI_CONFIG
}

if [ -d "$1" ]; then
   done_file="$1/requests.txt"
   touch $done_file
   for f in `find "$1" -name \*.csr -a -readable`; do
      rfp=`$ICI_OPENSSL req < $f | sha256sum | awk '{print $1}'`
      if [ "x$rfp" != "x" ]; then
         grep -q $rfp $done_file || {
            process_csr "$f"
            echo "$rfp:$f:`date`" >> $done_file
         }
      fi
   done
elif [ -f "$1" ]; then
   process_csr "$1" "$ICI_SUBJECT_DN"
else
   echo "*** Bad file type: $1" >&2
   exit 1
fi
