#!/bin/sh

if [ -z "$1" ]; then
   echo "Usage ${ICI_CMD} [options] publish <output dir>"
   exit 1
fi

PUBDIR="$1"
mkdir -p "$PUBDIR"
rsync -a "${ICI_CONF_DIR}/public_html/" "${PUBDIR}/"
. "${ICI_CONF_DIR}/lib/html.sh"

cp "${ICI_CA_DIR}/ca.crt" "${PUBDIR}"
if [ -f "${ICI_CA_DIR}/crl.pem" ]; then
   cp "${ICI_CA_DIR}/crl.pem" "${PUBDIR}"
else
   echo "*** WARNING - no CRL"
fi

(
html_index_head > "${PUBDIR}/index.html"
while read -r status date serial foo dn; do
   html_cert_file "$status" "$date" "$serial" "$foo" "$dn" > "${PUBDIR}/${serial}.html"
   html_index_entry "$status" "$date" "$serial" "$foo" "$dn" >> "${PUBDIR}/index.html"
   cp "${ICI_CA_DIR}/certs/${serial}.pem" "${PUBDIR}"
done
html_index_foot >> "${PUBDIR}/index.html"
) < "${ICI_CA_DIR}/index.txt"

