#!/bin/sh

if [ -z "$1" ]; then
   ${ICI_PRG} --help
   exit 0
fi

dir="${ICI_LIB_DIR}/$1.d"

if ! test -d "$dir"; then
    echo "Error: help: unknown command '$cmd'" 1>&2
    echo "Try 'ici help' for more information." 1>&2
    exit 1
fi

if ! test -f "$dir/help"; then
    echo "Error: help: not available for command '$cmd'" 1>&2
    echo "Try 'ici help' for more information." 1>&2
    exit 1
fi

cat "$dir/help" >&2
