#!/bin/sh

. $ICI_CA_DIR/ca.config

if [ "x`softhsm2-util --show-slots | grep \"Label:\\s*${ICI_CA_KEY_TOKEN}\"`" = "x" ]; then
    softhsm2-util --token "${ICI_CA_KEY_TOKEN}" --label "${ICI_CA_KEY_TOKEN}" \
		  --init-token --pin "${ICI_PKCS11_PIN}" --so-pin "${ICI_PKCS11_SOPIN}" \
		  --free
else
    echo "$0: SoftHSM2 already contains token with label '${ICI_CA_KEY_TOKEN}'"
fi
