#!/bin/sh

. $ICI_CONF_DIR/lib/config.sh
read_ca_config

$ICI_TRACE $ICI_OPENSSL req -new -x509 \
   -config $ICI_CONFIG -engine pkcs11 \
   -key "${ICI_CA_KEY_SLOT}:${ICI_CA_KEY_ID}" -keyform engine \
   -days ${ICI_DAYS:-3650} -set_serial 0 -out $ICI_CA_DIR/ca.crt
