#!/bin/sh

conf="${ICI_CA_DIR}/ca.config"
if [ ! -f "${conf}" ]; then
    cat>"${conf}"<<EOC
ICI_CA_KEY_TOKEN="ici-${ICI_CA_NAME}"
ICI_CA_KEY_LABEL="${ICI_CA_NAME}_key"
ICI_CA_KEY_ID=a1a2
ICI_PKCS11=/usr/lib/softhsm/libsofthsm2.so
ICI_PKCS11_PIN=secret
ICI_PKCS11_SOPIN=supersecret
ICI_MD=sha256
ICI_PUBLIC_URL=http://ca.example.com
# remove if no OCSP server is being set up
ICI_OCSP_URL=http://ocsp.example.com

# remove to disable softhsm
SOFTHSM2_CONF="$ICI_CA_DIR/softhsm/softhsm.conf"
export SOFTHSM2_CONF

# enable these lines to use PKCS#11 spy
#PKCS11SPY=${ICI_PKCS11}
#ICI_PKCS11=/usr/lib/x86_64-linux-gnu/pkcs11/pkcs11-spy.so
#export PKCS11SPY
EOC
else
    test "x$ICI_VERBOSE" = "xy" && echo "$0: File '${conf}' already exists, not overwriting"
fi
chmod 600 "${conf}"

touch "${ICI_CA_DIR}/index.txt"

policy="${ICI_CA_DIR}/name.policy"
if [ ! -f "${policy}" ]; then
    cat>"${policy}"<<EOC
[policy]
countryName 	       = match
stateOrProvinceName    = optional
organizationName       = supplied
organizationalUnitName = optional
commonName             = supplied
emailAddress           = optional
EOC
else
    test "x$ICI_VERBOSE" = "xy" && echo "$0: File '${policy}' already exists, not overwriting"
fi
