#!/bin/sh

cat>$ICI_CA_DIR/ca.config<<EOC
ICI_CA_KEY_ID=a1a2
ICI_CA_KEY_SLOT=0
ICI_PKCS11=/usr/lib/softhsm/libsofthsm.so
ICI_PKCS11_PIN=secret
ICI_MD=sha256
ICI_PUBLIC_URL=http://ca.example.com

# remove to disable softhsm
SOFTHSM_CONF=$ICI_CA_DIR/softhsm.conf
export SOFTHSM_CONF
EOC

touch "${ICI_CA_DIR}/index.txt"

cat>$ICI_CA_DIR/name.policy<<EOC
[policy]
countryName 	       = match 
stateOrProvinceName    = optional
organizationName       = supplied
organizationalUnitName = optional
commonName             = supplied
emailAddress           = optional
EOC
