#!/bin/sh

if [ -z "$1" -o -z "$2" ]; then
   echo "Error: revoke: Missing arguments" >&2
   ${ICI_PRG} help revoke
   exit 1
fi

mkdir -p $ICI_CA_DIR/certs

$ICI_OPENSSL ca -batch \
   -config $ICI_CONFIG -revoke "${ICI_CA_DIR}/certs/$1.pem" -crl_reason $2
